hypha-dao/hypha-wallet

- ios/Runner/Info.plist
iOS handles esr:// scheme
Testing: 
Push esr:// URL onto Safari browser - paste & go - it will open the wallet.
example URL
```
esr://gmNgYmBYlmzC9MoglIFhB9frlxK9jIwMEMAEpQVhAhwW5sZG5mZmZowJGSUlBVb6-okFmboFiZW5qXklehmVBRmJeqmJRSUZ-iVFiXnFicklmfl59qWZKbZJRinGFsmWqbqW5iZpuqYmZga6lhaWibpG5uYW5uaGBhYmiUlqJRXxQKXV1SUVtbUMAA
```
> Handle esr scheme

- lib/ui/blocs/authentication/authentication_bloc.dart
Unhandled Exception: Bad state: add(_$_OnAuthenticatedDataChanged) was called without a registered event handler.
^^ This is all you need to see where the issue is. This is again nothing to do with code generation, This can also happen when we create models without code generation.
What is wrong is that we call this event onUserProfileDataChanged but in the bloc we dont listen for this event
on<_OnAuthenticatedDataChanged>(_onAuthenticatedDataChanged); -> This line of code is missing.
This was an issue i added with the recent auth refactor.
> Auth bug - Fixed. 

- lib/core/crypto/dart_esr/src/encoding_options.dart
- lib/core/crypto/dart_esr/src/signing_request_manager.dart
- lib/core/crypto/dart_esr/src/utils/esr_constant.dart
- lib/core/crypto/seeds_esr/eos_transaction.dart
- lib/core/crypto/seeds_esr/seeds_esr.dart
- lib/core/network/api/eos_service.dart
- lib/core/network/api/remote_config_serivice.dart
- lib/ui/onboarding/import_account/usecases/find_account_use_case.dart
- lib/ui/sign_transaction/usecases/sign_transaction_use_case.dart
This is a major PR that adds support for other networks than Telos to our codebase. 
This is the first and most important aspect of it - all EOS Client access must specify the network it's running on. 
Providing Telos as a default is a way to not break existing code, but also temporary as eventually there won't be a default. 
Goal: Ability to parse any ESR code on any of our supported networks, and execute them, just as long as accounts and keys are present for that network. 
Other aspects of this:
- [Done] When providing an "abiProvider" we need to know the correct network. Abi provider accesses the provided node URL to download contract definitions (ABIs) and to resolve ESR encoded transactions. It's basically checking if the contract exists, if the action exists, and if the parameters …
> Multiple Network Support

- lib/core/local/services/crypto_auth_service.dart
Renamed some methods to indicate they are Seeds Global Passport compatibility. 
Added standard Bip39 seed method to create private keys from words. 
Not sure the later is "it" but need this code template to remember how it works.
> Mnemonic cleanup

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/ui/onboarding/onboarding_page.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
This PR enables  the app to launch URLs. 
This will allow us to launch Web urls, Mail URLs, Phone Urls. 
*Right now we only use web urls. *
URL schemes are only supported if there are apps installed on the device that can support them. For example, iOS simulators don't have a default email or phone apps installed, so can't open tel: or mailto: links.
> launch URL

- lib/ui/sign_transaction/success/sign_transaction_success_page.dart
Old text: 
Well Done!
The transaction was successfully approved.
New text: 
Success!
Transaction approved
Old text - well done - was weird because it implied the user was doing something - the app was doing something and is reporting back on success status. 
Also old text was longer while not actually adding any information that's not already on the green checkmark and our huge thumbs up ;)
> Replace some text

- lib/core/crypto/dart_esr/src/models/signing_request.dart
- lib/ui/sign_transaction/interactor/data/transaction_action_data.dart
Bug: 
Some transactions fail on expiration date parsing
Fix: 
Better date parsing, moved date parsing into SigningRequest class because the code is esoteric. All has to do with the structure of a signing request. 
```
final signRequestMap = data.esr.manager.signingRequest.req[1] as Map;
```
Would fail because sometimes that can be a List type object, causing a crash.
*** Steps to reproduce ***
In the DAO, redeem HUSD
*** Expected ***
It works
*** Actual ***
App crashes before showing the accept slider screen. 
*** Cause ***
Trying to cast List object to Map
> Fix expiration date parsing

- lib/ui/onboarding/import_account/import_words/import_account_by_words_view.dart
- lib/ui/onboarding/import_account/interactor/import_account_bloc.dart
more correct paste words.
Bug: 
Pasting 12 words separated by comma did not work
Fix: Simplified the code greatly & fixed, also show error messages, and don't accept longer or shorter word lists.
> fix for paste words

- lib/core/local/services/crypto_auth_service.dart
- test/mnemonic_key_test.dart
This PR adds method and links and unit test
Next PR will make change and also import all 3 possibilities. 
===============
So this was the best I could find how to generate a key from words for EOS
Set this website to "EOS" in the output
https://iancoleman.io/bip39/
I can also compare values there. 
We should use this going forward, then also import keys for all other methods.
> add more correct 12 words key import, unit tests

- ios/Podfile.lock
- lib/app.dart
- lib/core/crypto/dart_esr/src/signing_request_manager.dart
- lib/core/di/bloc_module.dart
- lib/core/local/services/crypto_auth_service.dart
- lib/ui/blocs/deeplink/deeplink_bloc.dart
- lib/ui/blocs/deeplink/deeplink_bloc.freezed.dart
- lib/ui/blocs/deeplink/deeplink_event.dart
- lib/ui/blocs/deeplink/deeplink_state.dart
- lib/ui/blocs/deeplink/page_command.dart
- lib/ui/blocs/push_notifications/push_notifications_bloc.dart
- lib/ui/home_page/interactor/home_bloc.dart
- lib/ui/home_page/usecases/parse_qr_code_use_case.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
I kept deep links exactly as before
Only ESR links are also handled. 
I feel this is safest to make sure the post-install app store link still works, but we can only test that once we're live.
I tested 4 different scenarios
- Cold start with ESR
- Cold start with firebase link
- ESR when app is in the background but running
- Deep link when app in background but running
All 4 work - Cold start with firebase link has an issue on iPhone simulator, but works on device - tested in build 18 on Testflight. 
Test URLs
ESR
```
esr://gmNgYmBYlmzC9MoglIFhB9frlxK9jIwMEMAEpQVhAhyWppZGhhZGRowJGSUlBVb6-okFmboFiZW5qXklehmVBRmJeqmJRSUZ-iVFiXnFicklmfl59qWZKbaGiUlJySbmybqpKUbJuqaWFqm6FqlJJrqpSWYpaeYWiYZJSeZqJRXxQKXV1SUVtbUMAA
```
Firebase (not a valid invite code BTW so this won't actually be able to …
> Handle esr and deep links

- lib/core/crypto/eosdart/src/numeric.dart
- lib/core/crypto/eosdart/src/serialize.dart
Fix for QR code scan bug #150
We should probably scan this messy code for more errors like that...
**Analysis**
Was able to get the underlying error by adding some more printouts
```
#3      SigningRequestUtils.deserializeAction
signing_request_manager.dart:750
#4      SigningRequestManager.resolveActions.<anonymous closure>
signing_request_manager.dart:392
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#9      new List.of (dart:core-patch/array_patch.dart:52:28)
#10     L<…>
flutter: error: Error processing QR code [Error …
```
> ESR bugfix

- lib/core/crypto/dart_esr/src/signing_request_manager.dart
- lib/ui/home_page/usecases/parse_qr_code_use_case.dart
- test/mocks/mock_hypha_preferences.dart
- test/mocks/mock_secure_storage_service.dart
- test/parse_esr_link_test.dart
- SigningRequestManager takes eosService parameter so it can be unit tested
- SigningRequestManager.isValidESRScheme used instead of text comparison of scheme (unifying code)
- unit tests for ESR parsing added - this will help us when we find more ESR codes that don't work
**Tested on device, everything still working**
> ESR cleanup and unit tests

- lib/ui/blocs/authentication/authentication_bloc.dart
Problem: deviceTokens was not being set reliably
Fix: Setting it any time auth data changes, covering login and app start. 
=====
Not sure this is the best place to do it - but in fact we need to store the device token any time the app starts, since it may start on a new phone for example. 
Also when authentication changes, we may have a new user, etc. 
We should probably check if the auth token is already set, and not do it if not needed - but maybe firebase does that internally? 
=====
Also we need to store account names with chain ID... 
example illum1nation:eos
Since account names are only unique to a single chain. We can make that change when we support multiple accounts.
> save device token on auth change

- lib/core/crypto/eosdart/src/serialize.dart
fixed the parameter so it can be null
EOSIO allows optional values 
setdaosetting has an optional string - denoted as type "string?" in the ABI of the contract
This caused Hypha Wallet to fail since the object was not set to nullable in the parameters
We introduced this bug when moving the entire crypto package eos_dart to be null safe
parameter needs to be nullable
I was checking this against the EOSJS JavaScript package which eosdart is based on.
Yes
Note that the action will still throw an exception since it has the wrong actor / permission, but it now throws an action/permission exception rather than a serialization exception. 
```
flutter: mapEosError: type 'Null' is not a subtype of type 'Object' of 'data'
flutter: stack: #0      _TypeError._throwNew …
```
> Fix for nullable parameter

- lib/core/network/api/aws_amplify/aws_authenticated_request.dart
- lib/core/network/api/services/dao_service.dart
- lib/core/network/api/services/user_account_service.dart
- lib/core/network/dio_exception.dart
- lib/core/network/networking_manager.dart
- lib/core/network/repository/transaction_history_repository.dart
- pubspec.lock
- pubspec.yaml
Default retryable status codes list 
Responses with this http status codes will be retried by default:
408: RequestTimeout
429: TooManyRequests
500: InternalServerError
502: BadGateway
503: ServiceUnavailable
504: GatewayTimeout
440: LoginTimeout (IIS)
460: ClientClosedRequest (AWS Elastic Load Balancer)
499: ClientClosedRequest (ngnix)
520: WebServerReturnedUnknownError
521: WebServerIsDown
522: ConnectionTimedOut
523: OriginIsUnreachable
524: TimeoutOccurred
525: SSLHandshakeFailed
527: RailgunError
598: NetworkReadTimeoutError
599: NetworkConnectTimeoutError
They will be retried Once, after a one second wait.
> Retry call when failed

- lib/core/crypto/dart_esr/src/signing_request_manager.dart
- lib/core/di/services_module.dart
- lib/core/network/api/aws_amplify/amplify_service.dart
- lib/core/network/api/aws_amplify/profile_upload_repository.dart
- lib/core/network/api/services/remote_config_service.dart
- lib/core/network/repository/auth_repository.dart
- lib/ui/onboarding/import_account/usecases/find_account_use_case.dart
- lib/ui/profile/interactor/profile_bloc.dart
- lib/ui/profile/usecases/initialize_profile_use_case.dart
- lib/ui/profile/usecases/ppp_sign_up_use_case.dart
- lib/ui/profile/usecases/profile_login_use_case.dart
- lib/ui/profile/usecases/remove_avatar_use_case.dart
- lib/ui/profile/usecases/set_bio_use_case.dart
- lib/ui/profile/usecases/set_image_use_case.dart
- lib/ui/profile/usecases/set_name_use_case.dart
- lib/ui/search_user/interactor/search_user_bloc.dart
- lib/ui/send/usecases/send_token_use_case.dart
- lib/ui/settings/interactor/settings_bloc.dart
- lib/ui/settings/usecases/delete_account_use_case.dart
- test/profile_upload_repository_test.dart
For your review
Seems like we could do something more elegant than using "network" everywhere
For example we could pass it around instead of accountName
The problem is now that network is stored in user profile, and I am not sure we always have one
If we always have one then we could always pass around a user profile, or an object with _only_ accountName and network everywhere, and not have this parameter pollute the whole code base. 
IDK
> [DRAFT] Full network support

- lib/core/crypto/eosdart/src/client.dart
- lib/core/logging/log_helper.dart
- lib/core/network/api/services/remote_config_service.dart
- lib/core/network/repository/profile_repository.dart
- lib/core/network/repository/transaction_history_repository.dart
- lib/ui/home_page/components/scanner_widget.dart
- lib/ui/onboarding/import_account/usecases/find_account_use_case.dart
The history plugin is officially deprecated and many nodes don't support it
This changes our account import to use a different call in the chain API - should be more stable. 
A couple of changes
- more widely supported way to import accounts - does not rely on the deprecated history plugin
- profile errors are not errors, just means no profile
- Loggers shall not throw errors that's just weird
Note: The new call can return accounts multiple times, when an account has owner and active keys that are the same, so it needs to de-duplicate the list.
> Update account import

- lib/core/crypto/eosdart/src/numeric.dart
- lib/core/di/log_module.dart
- lib/core/logging/log_helper.dart
- lib/core/network/api/eos_service.dart
- lib/core/network/models/dao_data_model.dart
- lib/ui/sign_transaction/interactor/sign_transaction_bloc.dart
- lib/ui/sign_transaction/usecases/sign_transaction_use_case.dart
Bug: ESR parser had another bug similar to the one before - my fix wasn't good enough
Fix: Now the fix is good enough. 
The string we had incoming that we were parsing was "-00" - this is a zero. 
The offending QR code:
> Bugix for set token multipliers transaction

- lib/core/network/api/services/dao_service.dart
So we can map a DAO id -> title (and other info, but for now we only need title)
> added getDaoById query

- .github/workflows/pull_request.yaml
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/ui/profile/components/profile_view.dart
- lib/ui/sign_transaction/failed/sign_transaction_failed_page.dart
- lib/ui/sign_transaction/interactor/page_command.dart
- lib/ui/sign_transaction/interactor/sign_transaction_bloc.dart
- lib/ui/sign_transaction/interactor/sign_transaction_bloc.freezed.dart
- lib/ui/sign_transaction/sign_transaction_page.dart
- lib/ui/sign_transaction/usecases/sign_transaction_use_case.dart
- pubspec.lock
> Wallet team feedback

- lib/ui/onboarding/onboarding_page.dart
Discussion:
On sign up, we used an internal app browser window.
Deep links don't work at all in Android in the internal browser window - it leads to an error page. 
Deep links work on iOS but the app would not close the browser window, so users had to hit "Done"
Fix:
We use an external browser, for the normal onboarding flow. 
This is the safest fix since opening the deep link does the right thing on all platforms, and we don't need to worry about app state either.
> Fix for DEV-1260 - open login page in external window

- lib/app.dart
- lib/ui/onboarding/onboarding_page.dart
- pubspec.yaml
Close the in app browser on onboarding link detected
This reverts a previous change where we changed to external browser - Apple App Review does not like opening external browsers, it's against the rules. 
So we now use in app and deployed a different solution to the original problem.
> Back to in app browser

- lib/ui/wallet/components/wallet_transaction_tile.dart
This PR improves the UI of the transaction card in the Wallet tab.
> Improve recent transaction card UI

- lib/core/crypto/eosdart/src/numeric.dart
bugfix at #150 deserializes all neg numbers as "-0". This PR fixes the shallow copy operation so that results are correct.
backported from Localscale wallet
Note: upstream PR at https://github.com/primes-network/eosdart/pull/47
> fix QR deserialization for negative big nums

- lib/ui/shared/hypha_body_widget.dart
Fixed an issue in the History Transaction screen where the bottom navigation bar was overlapping the last item in the list.
> fix: resolve navbar overlapping last item in list

- lib/ui/history/details/components/transaction_detail_view.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/294)
I fixed the issue by setting `scrolledUnderElevation` to `0`, which prevents the `AppBar` color from changing when scrolling on the transaction details page.
> fix: set AppBar scrolledUnderElevation to 0

- lib/design/themes/hypha_theme.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/298)
I set `statusBarBrightness` to `Brightness.light` for the `iOS light theme` to make the status bar icons dark.
> fix: status bar icon brightness for iOS light mode

- lib/core/di/bloc_module.dart
- lib/core/extension/proposals_filter_extension.dart
- lib/ui/proposals/filter/components/filter_proposals_view.dart
- lib/ui/proposals/filter/components/hypha_filter_card.dart
- lib/ui/proposals/filter/interactor/filter_proposals_bloc.dart
- lib/ui/proposals/filter/usecases/aggregate_dao_proposal_counts_use_case.dart
- lib/ui/proposals/filter/usecases/get_daos_from_proposal_counts_use_case.dart
- lib/ui/proposals/list/components/proposals_view.dart
- lib/ui/proposals/list/interactor/proposals_bloc.dart
- lib/ui/proposals/list/interactor/proposals_bloc.freezed.dart
- lib/ui/proposals/list/interactor/proposals_event.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/329)
I fixed the DAOs `ordering` on the `Filter Proposals` page and enabled the ability to `deselect` a DAO. The `proposals count` under each DAO now updates correctly.
> fix: filter proposals

- lib/ui/proposals/list/components/proposals_view.dart
Swap positions of the New Proposal button and the Filter button, with additional UI adjustments.
> refactor: Swap positions of the filter button and the new proposal button

- lib/ui/proposals/history/components/proposals_history_view.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/335)
I set `scrolledUnderElevation` to `0` to fix the `app bar color change`.
> fix: adjust app bar elevation

- lib/ui/proposals/filter/components/hypha_filter_card.dart
Updated the UI layout of the filter screen and fixed a UI bug that caused elements to display incorrectly
> refactor: Update filter screen ui

- ios/Podfile.lock
- lib/core/network/models/outcome_model.dart
- lib/ui/proposals/creation/components/hypha_outcome_card.dart
- lib/ui/proposals/creation/components/outcome_selection_view.dart
- lib/ui/proposals/creation/proposal_creation_page.dart
This PR implements the outcome type of proposal selection screen as part of the multi-step process for creating a new proposal.
> feat: Implement proposal outcome type selection screen

- lib/core/di/bloc_module.dart
- lib/core/network/models/outcome_model.dart
- lib/core/network/models/proposal_creation_model.dart
- lib/design/cards/hypha_option_card.dart
- lib/ui/proposals/creation/components/dao_selection_view.dart
- lib/ui/proposals/creation/components/hypha_outcome_card.dart
- lib/ui/proposals/creation/components/outcome_selection_view.dart
- lib/ui/proposals/creation/components/proposal_review_view.dart
- lib/ui/proposals/creation/interactor/proposal_creation_bloc.dart
- lib/ui/proposals/creation/proposal_creation_page.dart
- lib/ui/proposals/list/components/proposals_view.dart
- lib/ui/proposals/list/interactor/proposals_bloc.dart
This PR integrates the logic of proposal creation with the UI across all steps by centralizing state management using ProposalCreationBloc. Each screen now consumes data from previous steps, allowing for seamless navigation and dynamic UI updates. User selections, such as the outcome type, are passed forward. Bloc events efficiently handle interactions, ensuring data persistence and maintaining a single source of truth. Refactoring components like HyphaOutcomeCard for direct bloc interaction enhances code reusability and maintainability
> feat: Implemented navigation logic and dependency exchange for proposal creation steps

- lib/ui/proposals/creation/interactor/proposal_creation_bloc.dart
- lib/ui/proposals/creation/proposal_creation_page.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/354)
I've removed the proposal type selection page when creating a proposal, as the type is now set to `Agreement` by default.
> refactor: remove proposal type selection page

- lib/ui/proposals/list/components/hypha_proposals_action_card.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/367)
This PR is about making the proposal card clickable, redirecting users to the proposal details page when clicked, in addition to the button. It also updates the button text to `Vote` instead of `Details`.
> refactor: adjust proposal card redirection and button text

- lib/ui/proposals/list/proposals_page.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/365)
This PR resolves an issue where proposals load infinitely. The problem arises when you scan a QR code or create a proposal, and the app returns you to the first page (bottom navigation). In this case, the initial event for the proposals bloc is triggered again, but the success state is not emitted, resulting in proposals loading indefinitely.
> fix: proposals loading issue

- lib/ui/proposals/creation/components/dao_selection_view.dart
- lib/ui/proposals/creation/components/outcome_selection_view.dart
- lib/ui/proposals/creation/components/proposal_content_view.dart
- lib/ui/proposals/creation/components/proposal_review_view.dart
- lib/ui/proposals/creation/interactor/proposal_creation_bloc.dart
- lib/ui/proposals/creation/interactor/proposal_creation_bloc.freezed.dart
- lib/ui/proposals/creation/interactor/proposal_creation_event.dart
- lib/ui/proposals/creation/interactor/proposal_creation_state.dart
- lib/ui/proposals/creation/proposal_creation_page.dart
- lib/ui/proposals/details/components/proposal_details_view.dart
This PR focuses on optimizing the `ProposalCreationBloc` and ensuring that the `keyboard` is dismissed when navigating between views on the `ProposalCreationPage`.
> refactor: adjust proposal creation
