hypha-dao/hypha-wallet

lib/core/network/api/endpoints.dart, lib/core/network/api/user_account_service.dart, lib/core/network/repository/user_account_repository.dart, lib/design/progress_indicator/hypha_progress_logo.dart, test/user_account_service_test.dart
Added code to find valid user account
Fancy user account generator
Not perfect in terms of name - doesn't use '1' at all for long names.
However, it creates unique names in a sequence, so that's good enough for now.
=> create account name service

lib/core/di/bloc_module.dart, lib/core/di/di_setup.dart, lib/core/di/usecases_module.dart, lib/core/network/api/user_account_service.dart, lib/core/network/repository/user_account_repository.dart, lib/design/actionable_cards/hypha_actionable_card.dart, lib/ui/onboarding/create_account/components/create_account_view.dart, lib/ui/onboarding/create_account/interactor/create_account_bloc.dart, lib/ui/onboarding/usecases/find_available_account_use_case.dart, lib/ui/settings/settings_page.dart
missing await was the culprit. 
Some cleanup and UI updates
=> Fix Avail call and UI

lib/ui/home_page/components/scanner_widget.dart
Update UI to look like designs for scanner
=> Make Scanner ui look like designs

lib/ui/profile/components/profile_view.dart
https://github.com/hypha-dao/hypha_wallet/issues/39
=> Refresh button added to profile page on fail. 

lib/core/di/services_module.dart, lib/ui/profile/interactor/profile_data.dart, pubspec.yaml
1. Eos client url fixed
2. Dealing with no name in profile
3. Missing asset added
=> Small Fixes

lib/core/network/models/user_profile_data.dart, lib/core/network/models/user_profile_data.freezed.dart, lib/core/network/models/user_profile_data.g.dart, lib/ui/blocs/authentication/authentication_bloc.dart, lib/ui/home_page/components/home_view.dart, lib/ui/onboarding/import_account/components/user_account_list.dart, lib/ui/profile/interactor/profile_data.dart
Can the username be null? Yes? Then it should not be required in the model.
=> Fix null username

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/GoogleService-Info.plist, ios/Runner/Info.plist, ios/Runner/Runner.entitlements, lib/core/crypto/dart_esr/src/encoding_options.dart, lib/core/crypto/dart_esr/src/signing_request_manager.dart, lib/core/crypto/eosdart/eosdart.dart, lib/core/crypto/eosdart/src/serialize.dart, lib/core/crypto/seeds_esr/seeds_esr.dart, lib/core/di/di_setup.dart, lib/core/di/firebase_module.dart, lib/core/di/services_module.dart, lib/core/network/api/endpoints.dart, lib/core/network/api/eos_service.dart, lib/core/network/api/remote_config_serivice.dart, lib/core/network/api/transaction_history_service.dart, lib/core/network/api/user_account_service.dart, lib/core/network/networking_manager.dart, lib/core/network/repository/profile_repository.dart, lib/ui/onboarding/import_account/interactor/import_account_bloc.dart, lib/ui/profile/components/profile_view.dart, lib/ui/profile/interactor/profile_data.dart, pubspec.lock
added firebase config parameter with network endpoint data
also put the profile and create account URLs into firebase config
=> support all networks

ios/Podfile.lock, lib/ui/sign_transaction/interactor/data/transaction_action_data.dart, pubspec.yaml
Bug: 
When ESR has no expiration time set, app would crash (white screen)
Fix: 
Add default expiration time
=> fix for no expiration set

lib/core/di/bloc_module.dart, lib/core/di/di_setup.dart, lib/core/di/repositories_module.dart, lib/core/di/usecases_module.dart, lib/core/network/repository/auth_repository.dart, lib/ui/profile/components/profile_view.dart, lib/ui/profile/interactor/page_command.dart, lib/ui/profile/interactor/profile_bloc.dart, lib/ui/profile/interactor/profile_bloc.freezed.dart, lib/ui/profile/interactor/profile_data.dart, lib/ui/profile/interactor/profile_state.dart, lib/ui/profile/profile_page.dart, lib/ui/profile/usecases/initialize_profile_use_case.dart, lib/ui/profile/usecases/set_bio_use_case.dart
=> Edit profile Bio

lib/core/di/bloc_module.dart, lib/core/di/di_setup.dart, lib/core/di/usecases_module.dart, lib/core/network/api/aws_amplify/amplify_service.dart, lib/design/avatar_image/hypha_editable_avatar_image.dart, lib/ui/profile/components/profile_view.dart, lib/ui/profile/interactor/profile_bloc.dart, lib/ui/profile/interactor/profile_bloc.freezed.dart, lib/ui/profile/interactor/profile_data.dart, lib/ui/profile/interactor/profile_event.dart, lib/ui/profile/usecases/remove_avatar_use_case.dart, lib/ui/profile/usecases/set_image_use_case.dart
Fix: Displaced Delete Image icon
Add: Initial Bio when editing
Remove Avatar
=> Fix icon UI and text initial + Remove avatar

lib/app.dart, lib/core/di/usecases_module.dart, lib/core/network/repository/auth_repository.dart, lib/design/avatar_image/hypha_avatar_image.dart, lib/design/progress_indicator/hypha_partial_progress_indicator.dart, lib/design/secret_phrase/hypha_secret_phrase.dart, lib/design/themes/app_bottom_navigation_theme.dart, lib/design/themes/hypha_theme.dart, lib/ui/bottom_navigation/components/bottom_navigation_view.dart, lib/ui/home_page/components/home_view.dart, lib/ui/onboarding/create_account_success_page.dart, lib/ui/onboarding/create_profile/create_profile_page.dart, lib/ui/onboarding/import_account/import_words/import_account_by_words_view.dart, lib/ui/onboarding/import_account/interactor/import_account_bloc.dart, lib/ui/onboarding/import_account/interactor/import_account_bloc.freezed.dart, lib/ui/onboarding/import_account/interactor/import_account_state.dart, lib/ui/onboarding/onboarding_page.dart, lib/ui/profile/components/profile_view.dart, lib/ui/profile/interactor/profile_bloc.dart, lib/ui/profile/interactor/profile_data.dart, lib/ui/profile/usecases/set_image_use_case.dart, lib/ui/settings/save_key_page.dart, lib/ui/settings/save_words_page.dart, lib/ui/sign_transaction/failed/sign_transaction_failed_page.dart, lib/ui/sign_transaction/success/sign_transaction_success_page.dart
Add image from Edit image page.
@nik We need to return the image URL on that call. Is it possible?
=> Edit profile: Add image

lib/ui/onboarding/onboarding_page.dart
Buttons too far down
Before
After
=> safe area for intro screen

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, lib/ui/profile/components/profile_view.dart, pubspec.lock, pubspec.yaml
https://github.com/hypha-dao/hypha_wallet/issues/137
=> Allow for image cropping in profile page

android/app/src/main/AndroidManifest.xml, lib/core/firebase/firebase_push_notifications_service.dart, lib/ui/blocs/push_notifications/push_notifications_bloc.dart
Handle push notification for ANDROID tested
✅  App is open
✅ ] App is backgrounded
❎  App is terminated
If fails to receive the push notification when app is terminated
=> Push notification handle

lib/core/di/bloc_module.dart, lib/core/di/di_setup.dart, lib/ui/send/components/send_view.dart, lib/ui/send/interactor/page_command.dart, lib/ui/send/interactor/send_bloc.dart, lib/ui/send/interactor/send_bloc.freezed.dart, lib/ui/send/interactor/send_event.dart, lib/ui/send/interactor/send_state.dart, lib/ui/send/send_page.dart
Initial Send flow. Not connected to UI yet. Can be merged.
=> Initial Send flow

lib/ui/settings/interactor/settings_bloc.dart, lib/ui/settings/interactor/settings_bloc.freezed.dart, lib/ui/settings/interactor/settings_state.dart, lib/ui/settings/settings_view.dart, pubspec.lock, pubspec.yaml
Missing designs. Code to fetch the app version added.
=> Added app version

ios/Podfile.lock, lib/core/di/di_setup.dart, lib/core/di/services_module.dart, lib/core/network/api/services/dao_service.dart, lib/core/network/api/services/remote_config_service.dart, lib/core/network/models/dao_data_model.dart
Provides a service calls to fetch all DAOs an account is part of 
We should store the network along with the account for all accounts, so we always know which network to use. 
We can start assuming "telos" for any accounts we didn't store this data as a default. 
The logo comes as IPFS hash, like this:
Settings Logo: QmbyW3yY7jTjUi6XCkSy5GMsPDtonXBQ6e5nTFj3Dh6P9z:jpeg
To show this logo, we can use ipfs_http_client
```
dependencies:
flutter:
sdk: flutter
http: ^0.13.4
ipfs_http_client: ^0.1.0
flutter_image: ^1.1.0
=======================
import 'package:http/http.dart' as http;
import 'package:ipfs_http_client/ipfs_http_client.dart';
// IPFS hash from your response
final ipfsHash = 'QmbyW3yY7jTjUi6XCkSy5GMsPDtonXBQ6e5nTFj3Dh6P9z';
// Create an instance of IPFS client
final ipfsClient = …
```
=> Get all DAOs for a member

lib/core/di/usecases_module.dart, lib/core/network/api/aws_amplify/amplify_service.dart, lib/ui/profile/interactor/profile_bloc.dart, lib/ui/profile/usecases/profile_login_use_case.dart, lib/ui/profile/usecases/set_name_use_case.dart, lib/ui/settings/usecases/delete_account_use_case.dart
bug: set name didn't work
fix: need to login to ppp service first, just like set image and set bio
=> set name forces login on ppp service

lib/core/di/services_module.dart, lib/core/network/api/services/hypha_member_service.dart, lib/core/network/api/services/pay_cpu_service.dart, lib/core/network/api/services/remote_config_service.dart, lib/core/network/repository/user_account_repository.dart, lib/ui/search_user/interactor/search_user_bloc.dart, lib/ui/search_user/usecases/search_for_user_use_case.dart
**Note**
Merge after https://github.com/hypha-dao/hypha_wallet/pull/210
**What is this for**
- add HyphaMemberService isMember method
- add network to member service
- add dao and pay cpu contract to remote config
- add PayForCpuService - this has an action you need to use to preload to the list of actions 
- fix graph QL endpoints - not really part of this PR but since I was adding data...
=> add pay CPU action

lib/ui/sign_transaction/components/sign_transaction_view.dart, lib/ui/sign_transaction/interactor/data/transaction_action_data.dart
=> Pay CPU UI

.gitignore, lib/ui/splash/splash_page.dart, pubspec.yaml, upload_ios_build.sh
=> Remove bounce up animation

lib/app.dart, lib/core/di/bloc_module.dart, lib/ui/blocs/deeplink/deeplink_bloc.dart, lib/ui/blocs/deeplink/deeplink_bloc.freezed.dart, lib/ui/blocs/deeplink/deeplink_event.dart, lib/ui/onboarding/create_account/create_account_page.dart, lib/ui/settings/interactor/settings_bloc.dart
Handle parsing error ESR link
Handle when the user taps on a ESR link but no account is active.
=> No account found

android/build.gradle, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/ui/home_page/components/scanner_widget.dart, pubspec.lock, pubspec.yaml
updating all firebase packages, and kotlin version 
Note: need to redo iOS pods after this
=> package update for deep links and all other firebase things

lib/ui/onboarding/create_account_success_page.dart, lib/ui/onboarding/edit_account/edit_account_page.dart
Bug: didn't clear invite link on account edit page
We only did it on account create page.
=> Fix for #251

lib/ui/home_page/components/scanner_widget.dart
=> Slow scanning fix

lib/core/firebase/firebase_database_service.dart
Some update functions for user data in firebase were not working for new users
using set.. with merge instead of update fixes this issue.
=> Handle new users correctly

ios/Runner/AppDelegate.swift, lib/ui/bottom_navigation/components/bottom_navigation_view.dart, lib/ui/profile/components/dao_widget.dart, lib/ui/proposals/list/components/hypha_proposals_action_card.dart, lib/ui/proposals/list/components/proposals_view.dart, lib/ui/shared/hypha_body_widget.dart, pubspec.lock, pubspec.yaml
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/291)
- Fixed margin issue on the bottom navbar to ensure it doesn’t obscure content.
- Adjusted body layout to prevent background color from showing around the navbar.
- Made DAO name visible on the proposal card in light mode.
- Resolved overflow issue on the profile screen.
=> fix: Resolve various UI bugs

lib/ui/proposals/filter/components/filter_view.dart, lib/ui/proposals/filter/components/hypha_filter_card.dart, lib/ui/proposals/filter/filter_page.dart, lib/ui/proposals/list/components/proposals_view.dart
In this PR I implemented the UI for the proposals filter screen
Light            |  Dark
=> feat: Implement filter screen UI

lib/core/network/models/base_proposal_model.dart, lib/design/avatar_image/hypha_avatar_image.dart, lib/ui/proposals/components/proposal_creator.dart, lib/ui/proposals/details/components/proposal_voters.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/311)
I have removed `Json keys` and add creator and voter `names` to `placeholder` display.
=> refactor: remove Json keys and add creator and voter names to placeholder display

lib/core/extension/string_extension.dart, lib/core/network/models/proposal_details_model.dart
some whitespace fixes made by the IDE formatter
=> add accessors to proposal model

lib/core/extension/base_proposal_model_extension.dart, lib/ui/proposals/details/components/proposal_details_view.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/320)
I have removed the `s` from the `proposal details` page when there is a `single cycle`.
=> refactor: remove s

lib/core/network/repository/proposal_repository.dart, lib/ui/proposals/list/interactor/get_proposals_use_case_input.dart, lib/ui/proposals/list/interactor/proposals_bloc.dart, lib/ui/proposals/list/usecases/get_proposals_use_case.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/325)
I have refactored the `GetProposalsUseCase` to inherit from the `InputUseCase` base class.
=> refactor: add extends InputUseCase

lib/core/di/bloc_module.dart, lib/core/di/di_setup.dart, lib/ui/proposals/components/proposals_list.dart, lib/ui/proposals/history/components/proposals_history_view.dart, lib/ui/proposals/history/interactor/proposals_history_bloc.dart, lib/ui/proposals/history/interactor/proposals_history_bloc.freezed.dart, lib/ui/proposals/history/interactor/proposals_history_event.dart, lib/ui/proposals/history/interactor/proposals_history_state.dart, lib/ui/proposals/history/proposals_history_page.dart, lib/ui/proposals/list/components/proposals_view.dart, lib/ui/proposals/list/interactor/proposals_bloc.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/319)
I have implemented the proposals history page along with its corresponding logic.
=> feat: implement proposals history

lib/core/di/repositories_module.dart, lib/core/network/api/actions/vote_action_factory.dart, lib/core/network/repository/proposal_repository.dart, lib/ui/profile/usecases/fetch_profile_use_case.dart, lib/ui/proposals/details/components/proposal_details_view.dart, lib/ui/proposals/details/interactor/proposal_detail_bloc.dart, lib/ui/proposals/details/interactor/proposal_detail_bloc.freezed.dart, lib/ui/proposals/details/interactor/proposal_detail_event.dart, lib/ui/proposals/details/usecases/get_proposal_details_use_case.dart, lib/ui/proposals/list/components/hypha_proposals_action_card.dart
This PR implements the functionality for users to vote on proposals. The key features included are:
- **Vote Casting:** Users can cast their votes on proposals.
- **Vote Modification:** Users have the ability to change their votes if they wish to update their selection.
- **UI Updates:** Updated the user interface to reflect the voting status.
=> feat: handle vote casting

lib/design/cards/hypha_option_card.dart, lib/ui/proposals/creation/components/dao_selection_view.dart, lib/ui/proposals/filter/components/filter_proposals_view.dart, lib/ui/proposals/list/components/proposals_view.dart, lib/ui/proposals/list/interactor/proposals_bloc.dart
This PR implements the DAO selection screen as part of the multi-step process for creating a new proposal. This screen enables users to select the desired DAO to which the proposal will be submitted.
=> feat: Implement dao selection screen

lib/design/cards/hypha_option_card.dart, lib/design/themes/hypha_theme.dart, lib/ui/proposals/filter/components/filter_proposals_view.dart, lib/ui/proposals/filter/interactor/filter_proposals_bloc.dart, lib/ui/proposals/filter/interactor/filter_proposals_bloc.freezed.dart, lib/ui/proposals/filter/interactor/filter_proposals_event.dart, lib/ui/proposals/list/interactor/proposals_bloc.freezed.dart
[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/357)
This pull request implements the refactoring of the Filter Proposals feature to align with the new Figma design specifications. Below are the key updates made to improve the user interface and functionality:
**1. DAOs Filter**:
* **Checkbox Integration**: DAOs are now displayed as checkboxes.
* **Default Selection**: All DAOs are pre-selected when the filter screen opens.
* **Selection Constrain**t: Ensures at least one DAO remains selected at all times, preventing users from deselecting all DAOs.
**2. Status Filter**:
* **Repositioning**: The Past/Active status selection has been moved to the top.
* **Title Update**: The status filter section is renamed from “Filter by status” to “Select Proposal Status” and the DAOs filter …
=> refactor: filter proposals
